id: CF_Fixture_Dependency_Parent
name: CF Fixture - Dependency Parent
description: "Fixture parent playbook that calls a child playbook by UUID playbookId (used to test id->name normalization + dependent rewrite)."
version: -1
fromversion: 6.5.0
tags: []
type: playbook
tasks:
  "0":
    id: "0"
    taskid: "00000000-0000-0000-0000-000000000000"
    type: start
    task:
      id: "0"
      name: Start
      description: ""
      version: -1
      iscommand: false
      brand: ""
    nexttasks:
      "#none#":
        - "1"

  "1":
    id: "1"
    taskid: "11111111-1111-1111-1111-111111111111"
    type: playbook
    task:
      id: "1"
      name: Call Child (by UUID)
      description: "Calls the child playbook using playbookId UUID to test dependent rewrites."
      version: -1
      iscommand: false
      brand: ""
      playbookId: "11111111-2222-3333-4444-555555555555"
      playbookName: "CF Fixture - Dependency Child"
    nexttasks:
      "#none#":
        - "2"

  "2":
    id: "2"
    taskid: "22222222-2222-2222-2222-222222222222"
    type: title
    task:
      id: "2"
      name: Done
      description: ""
      version: -1
      iscommand: false
      brand: ""
    nexttasks: {}
